# docker compose file for running a 3-node PostgreSQL cluster
# with 3-node etcd cluster as the DCS and one haproxy node
version: "2"
services:

    etcd1:
        image: quay.io/coreos/etcd:v3.4.0
        env_file: etcd1.env
        container_name: etcd1
        network_mode: "host"
        hostname: etcd1
        command: etcd -name etcd1 -initial-advertise-peer-urls http://192.168.1.15:2380 -advertise-client-urls http://192.168.1.15:2379
        volumes:
          - /etcd-data/etcd1/:/home/postgres/etcd1.data
        ports:
            - "2380:2380"
            - "2379:2379"
