# docker compose file for running a 3-node PostgreSQL cluster
# with 3-node etcd cluster as the DCS and one haproxy node
version: "2"
services:
    haproxy:
        image: patroni
        networks:
          cluster_net:
            ipv4_address: 192.168.1.13
        hostname: haproxy
        container_name: haproxy
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - "5000:5000"
            - "5001:5001"
            - "7000:7000"
        command: haproxy
